default_repository: github
# will be stored at cache_dir/repository/file
cache_dir: $HOME/.cache/fetch-ignore/
repositories:
  - name: github
    type: git-repository
    source: ssh://git@github.com:github/gitignore.git
  - name: github-raw
    type: http
    source: "https://raw.githubusercontent.com/github/gitignore/master/{{.Lang}}.gitignore"
    cache: 30days # default: 0 means no cache
  - name: github
    type: file
    source: $CACHE_DIR/$(sha1-of-source)/Community/{{.Lang}}.gitignore
